version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./api:/app  # For hot reloading if in development
  
  frontend:
    build:
      context: .
      dockerfile: warehouse-manager/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge